import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/lib/components/organisms/Header";
import Footer from "@/lib/components/organisms/Footer";
import ColorBar from "@/lib/components/molecules/Colorbar";
import Card from "@/lib/components/molecules/Card";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export const metadata: Metadata = {
  title: "ADTV Tanzschule Lambertz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <div className="fixed inset-0 z-0 overflow-hidden">
          <video
            className="w-full h-full object-cover"
            src="/chacha.mp4"
            autoPlay
            muted
            loop
            playsInline
          />
          <div className="absolute inset-0 bg-white/10 backdrop-blur-md" />
        </div>

        <div className="relative z-10 min-h-screen flex flex-col">
          <Header />
          <ColorBar />
          <main className="flex-grow px-4 lg:px-40 py-6">
            <div className="min-h-[calc(100vh-theme(spacing.24))]flex items-center justify-center">
              <Card hover={false} className="shadow-xl">
                {children}
              </Card>
            </div>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
